name: 'Dotnet Compat Checker'
description: 'Checks the ABI compatibility between two .NET assemblies.'
author: 'wolfcomp'
branding:
    icon: 'activity'
    color: 'blue'
inputs:
    left:
        description: 'The path to the left assembly.'
        required: true
    right:
        description: 'The path to the right assembly.'
        required: true
    token:
        description: 'The GitHub token to use for the check.'
        default: ${{ github.token }}
        required: false
    tag:
        description:
            'The tag(s) to add to the pull request if check fails. Comma
            separated.'
        default: ''
        required: false
runs:
    using: node20
    main: dist/index.js
